[package]
name = "xenonc"
version = "0.1.0"
edition = "2024"
description = "Xenon compiler (xenonc)"
license = "MPL-2.0"
publish = false

[dependencies]
clap = { version = "4.5.60", features = ["derive"] }
logos = "0.16.1"
